### ISSUE TITLE
slmfit fails on simulated data

### ISSUE THREAD

**Issue by brycefrank** [highamm/sptotal#3]
Matt,

Like we discussed earlier today. Leaving this issue here for tracking.

The following simulation lead to an error using `slmfit`. Here is the code:

```{r}
pop197 <- read.csv('sims/h10_l10/197.csv')
slmfit(z~x+y, xcoordcol="x", ycoordcol="y", data=pop197, CorModel="Exponential")
```

However, it does not fail using "Spherical"

```{r}
pop197 <- read.csv('sims/h10_l10/197.csv')
slmfit(z~x+y, xcoordcol="x", ycoordcol="y", data=pop197, CorModel="Spherical")
```

Nor does it fail for maximum likelihood:

```{r}
pop197 <- read.csv('sims/h10_l10/197.csv')
slmfit(z~x+y, xcoordcol="x", ycoordcol="y", data=pop197, estmethod = "ML")
```

The csv is attached:
[197.csv.zip](https://github.com/highamm/sptotal/files/2980448/197.csv.zip)

**Comment by highamm** [comment]
Hey Bryce! Thanks for putting this together. I believe the issue should be fixed. We were using diagonalization to stabilize covariance matrices with very small nuggets, but in a later part of the function. So, it wasn't really helping us at all. I added a line to the `m2LL.FPBK.nodet.R` function that diagonalizes the covariance matrix by adding a small nugget value (1e-6). 

Also, the argument, `coordtype = "UTM"` should be added to the `slmfit` code, since we have the default coordinate system being Latitude/Longitude. So the function is converting your simulated coordinates from Lat/Lon to UTM when there is no need for it to do so.

Thanks!
Matt
